
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: monster_development

test:
  <<: *default
  database: monster_test


production:
  <<: *default
  database: monster_production
  username: monster
  password: <%= ENV['MONSTER_DATABASE_PASSWORD'] %>
